src/Entity/Business.php
<?php

namespace App\Entity;

use App\Repository\BusinessRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Monolog\DateTimeImmutable;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Exception;

/**
 * @ORM\Entity(repositoryClass=BusinessRepository::class)
 * @Vich\Uploadable()
 */
class Business implements \Serializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Image(mimeTypes={"image/png", "image/jpeg"})
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="business_image", fileNameProperty="image")
     * @Assert\Image(mimeTypes={"image/png", "image/jpeg"}, maxSize="2M")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $phone_number;

    /**
     * @ORM\OneToOne(targetEntity=User::class, inversedBy="business", cascade={"persist"})
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity=Commodity::class, mappedBy="business", cascade={"persist", "remove"})
     */
    private $commodities;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    public function __construct()
    {
        $this->commodities = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getImageFile() {
        return $this->imageFile;
    }

    /**
     * @param mixed $imageFile
     * @return Business
     */
    public function setImageFile($imageFile) {
        $this->imageFile = $imageFile;

        if($imageFile != null) {
            $this->updatedAt = new \DateTimeImmutable();
        }

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(?string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Commodity[]
     */
    public function getCommodities(): Collection
    {
        return $this->commodities;
    }

    public function addCommodity(Commodity $commodity): self
    {
        if (!$this->commodities->contains($commodity)) {
            $this->commodities[] = $commodity;
            $commodity->addBusiness($this);
        }

        return $this;
    }

    public function removeCommodity(Commodity $commodity): self
    {
        if ($this->commodities->removeElement($commodity)) {
            $commodity->removeBusiness($this);
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function serialize()
    {
        return serialize([
            'id' => $this->id,
        ]);
    }

    public function unserialize($serialized)
    {
        list (
            $this->id,
            ) = array_values(unserialize($serialized));
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}

src/Entity/Command.php
<?php

namespace App\Entity;

use App\Repository\CommandRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandRepository::class)
 */
class Command
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_command;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="commands")
     */
    private $user;

    /**
     * @ORM\Column(type="float")
     */
    private $total;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToMany(targetEntity=Commodity::class, inversedBy="commands")
     */
    private $commodity;

    public function __construct()
    {
        $this->commodity = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbCommand(): ?int
    {
        return $this->nb_command;
    }

    public function setNbCommand(int $nb_command): self
    {
        $this->nb_command = $nb_command;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getTotal(): ?float
    {
        return $this->total;
    }

    public function setTotal(float $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|Commodity[]
     */
    public function getCommodity(): Collection
    {
        return $this->commodity;
    }

    public function addCommodity(Commodity $commodity): self
    {
        if (!$this->commodity->contains($commodity)) {
            $this->commodity[] = $commodity;
        }

        return $this;
    }

    public function removeCommodity(Commodity $commodity): self
    {
        $this->commodity->removeElement($commodity);

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @Vich\Uploadable()
 */
class User implements \Symfony\Component\Security\Core\User\UserInterface, \Serializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     * @Assert\Image(mimeTypes={"image/png", "image/jpeg"})
     */
    private $avatar;

    /**
     * @Vich\UploadableField(mapping="avatar", fileNameProperty="avatar")
     * @Assert\Image(mimeTypes={"image/png", "image/jpeg"}, maxSize="2M")
     */
    private $avatarFile;


    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $balance;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\OneToOne(targetEntity=Business::class, mappedBy="user", cascade={"persist", "remove"})
     */
    private $business;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\OneToOne(targetEntity=Cart::class, inversedBy="user", cascade={"persist", "remove"})
     */
    private $cart;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $createdAt;

    /**
     * @ORM\OneToMany(targetEntity=Command::class, mappedBy="user")
     */
    private $commands;

    public function __construct()
    {
        $this->commands = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getAvatarFile() {
        return $this->avatarFile;
    }

    /**
     * @param mixed $avatarFile
     * @return User
     */
    public function setAvatarFile($avatarFile) {
        $this->avatarFile = $avatarFile;

        if($avatarFile != null) {
            $this->updatedAt = new \DateTimeImmutable();
        }

        return $this;
    }

    public function getBalance(): ?float
    {
        return $this->balance;
    }

    public function setBalance(?float $balance): self
    {
        $this->balance = $balance;

        return $this;
    }

    public function getRoles(): ?array
    {
        $roles = $this->roles;

        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function getUsername()
    {
        // TODO: Implement getUsername() method.
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getBusiness(): ?Business
    {
        return $this->business;
    }

    public function setBusiness(?Business $business): self
    {
        // unset the owning side of the relation if necessary
        if ($business === null && $this->business !== null) {
            $this->business->setUser(null);
        }

        // set the owning side of the relation if necessary
        if ($business !== null && $business->getUser() !== $this) {
            $business->setUser($this);
        }

        $this->business = $business;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function serialize()
    {
        return serialize([
            'id' => $this->id,
            'email' => $this->email,
            'password' => $this->password,
        ]);
    }

    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->email,
            $this->password
            ) = array_values(unserialize($serialized));
    }

    public function getCart(): ?Cart
    {
        return $this->cart;
    }

    public function setCart(?Cart $cart): self
    {
        $this->cart = $cart;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|Command[]
     */
    public function getCommands(): Collection
    {
        return $this->commands;
    }

    public function addCommand(Command $command): self
    {
        if (!$this->commands->contains($command)) {
            $this->commands[] = $command;
            $command->setUser($this);
        }

        return $this;
    }

    public function removeCommand(Command $command): self
    {
        if ($this->commands->removeElement($command)) {
            // set the owning side to null (unless already changed)
            if ($command->getUser() === $this) {
                $command->setUser(null);
            }
        }

        return $this;
    }

}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstname', TextType::class, [
                'label' => 'Prénom :'
            ])
            ->add('lastname', TextType::class, [
                'label' => 'Nom :'
            ])
            ->add('email', TextType::class, [
                'label' => 'Email :'
            ])
            ->add('avatarFile', VichImageType::class, [
                'label' => 'Image de profil :',
                'required' => false,
                'allow_delete' => true,
                'delete_label' => "Supprimer l'image",
                'download_uri' => true,
                'download_label' => "Télécharger l'image",
                'image_uri' => true,
                'asset_helper' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

class UserController extends AbstractController
{
    /**
     * @Route("/profile", name="profile")
     * @Route("/user/{id}", name="user_profile")
     */
    public function index(User $user = null): Response
    {
        $user ??= $this->getUser();
        $business = $user->getBusiness();
        $commands = $user->getCommands();

        if ( ! $user) {
            return $this->redirectToRoute('login');
        }

        return $this->render('user/index.html.twig', [
            'user' => $user,
            'business' => $business,
            'commands' => $commands
        ]);
    }

    /**
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     * @Route("/profile/update", name="user_edit")
     */
    public function edit(Request $request, EntityManagerInterface $manager) {

        /** @var UserInterface $user */
        $user = $this->getUser();
        $userForm = $this->createForm(UserType::class, $user);
        $userForm->handleRequest($request);

        if($userForm->isSubmitted() && $userForm->isValid()) {
            $manager->persist($user);
            $manager->flush();
            return $this->redirectToRoute('profile');
        }

        return $this->render('user/form.html.twig', [
            'form' => $userForm->createView(),
            'user' => $user
        ]);
    }
}

templates/user/form.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ parent() }} Formulaire de {{ user.firstname }} {{ user.lastname }}{% endblock %}

{% block body %}
    <div class="container">
        <h2>FORMULAIRE D'UTILISATEUR</h2>
        <h3>{{ user.firstname }} {{ user.lastname }}</h3>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button type="submit" class="btn btn-success mr-4"><i class="fas fa-check mr-2"></i>Confirmer</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{parent()}} Mon profil{% endblock %}

{% block body %}
    <div class="container">

    {% set is_current_user = app.user == user %}
    <section class="row my-4 mb-3">
        <div class="col col-4 col-sm-5 col-md-3 col-lg-3">
            <img class="img-fluid"
                 src="{{ user.avatar ? vich_uploader_asset(user, 'avatarFile') : 'http://placehold.it/300x300' }}"
                 alt="Avatar">
            {% if is_granted('ROLE_ADMIN') %}
                <a class="btn btn-danger mt-2" href="{{ path('admin') }}"><i class="fas fa-user"></i></a>
            {% endif %}
        </div>
        <div class="col col-8 col-sm-7 col-md-9 col-lg-9">
            <h2>{{ user.firstname }} {{ user.lastname }}</h2>
            <p>{{ user.email }}</p>
            {% if is_current_user %}
                <a class="btn btn-warning" href="{{ path('user_edit', {id: user.id}) }}"><i class="fas fa-pencil mr-2"></i>Editez votre profil</a>
                <br>
                <a class="btn btn-sm btn-danger mt-2" href="{{ path('logout') }}"><i
                            class="fas fa-power-off mr-2"></i>Déconnexion</a>
            {% endif %}
        </div>
        <div class="mt-3 ml-3">
            <h4>MES COMMANDES EFFECTUÉES</h4>
            {% if commands.count == 0 %}
                <h5>Aucune commande effectuée</h5>
            {% else %}
                <h5>{{ commands.count }} commande{% if commands.count > 1 %}s{% endif %} effectuée{% if commands.count > 1 %}s{% endif %}</h5>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">N. commande</th>
                                <th scope="col">Date</th>
                                <th scope="col">Total</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for command in commands %}
                            <tr>
                                <th scope="row">{{ command.nbCommand }}</th>
                                <td>{{ command.createdAt|date('d-m-y') }}</td>
                                <td>{{ command.total }} €</td>
                                <td><a href="{{ path('command', {id: command.id}) }}" class="btn btn-primary"><i class="fas fa-eye"></i></a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
        </div>
        <div class="mt-3 ml-3">
        {% if user.business != null %}
            <h4 class="mt-4">{% if is_current_user %}MON COMMERCE{% else %}COMMERCE{% endif %}</h4>
            <div style="width: 100%">
                <div class="card w-100 radius">
                    <img class="card-img-top" src="{{ business.image ? vich_uploader_asset(business, 'imageFile') : 'http://placehold.it/300x100' }}" alt="Commerce image" style="width: 100%; height: 150px">
                    <div class="card-body">
                        <h5 class="card-title">{{ business.name }}</h5>
                        <i>{{ business.address }}<br /></i>
                        <i>{{ business.phoneNumber }}</i>
                        <p class="card-text mt-2">{{ business.description }}</p>
                        <div class="btn-group">
                            <a class="btn btn-primary mr-2" href="{{ path('business_detail', {id: business.id}) }}"><i class="fas fa-list mr-2"></i>Voir les produits </a>
                            {% if is_current_user %}
                                <a href="{{ path('business_edit', {id: business.id}) }}" class="btn btn-warning"><i class="fas fa-pencil mr-2"></i>Gestion du commerce</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
        </div>

    </section>
    </div>

    {#    <section>#}
{#        {% if is_current_user %}#}
{#            <h3>Mes jeux</h3>#}
{#        {% else %}#}
{#            <h3>Les jeux de {{ user.firstname }}</h3>#}
{#        {% endif %}#}
{#        <table class="table">#}
{#            <thead>#}
{#            <tr>#}
{#                <th scope="col">Jeux</th>#}
{#                {% if is_current_user %}#}
{#                    <th scope="col">Action</th>#}
{#                {% endif %}#}
{#            </tr>#}
{#            </thead>#}
{#            <tbody>#}
{#            {% for game in user.games %}#}
{#                <tr>#}
{#                    <td>#}
{#                        <a href="{{ path('game_details', { id: game.id }) }}">{{ game.name }}</a>#}
{#                    </td>#}
{#                    <td>#}
{#                        {% if is_current_user %}#}
{#                            <a href="{{ path('game_edit', { id: game.id }) }}" class="btn btn-warning"><i#}
{#                                        class="fas fa-pen"></i></a>#}
{#                        {% endif %}#}
{#                    </td>#}
{#                </tr>#}
{#            {% endfor %}#}
{#            </tbody>#}
{#        </table>#}
{#    </section>#}
{% endblock %}